apiVersion: v1
kind: Secret
metadata:
  name: monitoring-grid-secrets
  namespace: monitoring-grid
type: Opaque
stringData:
  # Database connections (base64 encoded in production)
  DefaultConnection: "Server=sqlserver-service;Database=MonitoringGrid;User Id=sa;Password=CHANGE_ME_IN_PRODUCTION;TrustServerCertificate=true;"
  PopAIConnection: "Server=sqlserver-service;Database=PopAI;User Id=sa;Password=CHANGE_ME_IN_PRODUCTION;TrustServerCertificate=true;"
  RedisConnection: "redis-service:6379,password=CHANGE_ME_IN_PRODUCTION"
  
  # JWT Configuration
  JwtSecretKey: "CHANGE_ME_TO_A_SECURE_256_BIT_KEY_IN_PRODUCTION"
  
  # Encryption keys
  EncryptionKey: "CHANGE_ME_32_CHARACTER_KEY_PROD"
  HashingSalt: "CHANGE_ME_32_CHARACTER_SALT_PROD"
  
  # Email configuration
  SmtpUsername: "your-smtp-username"
  SmtpPassword: "your-smtp-password"
  
  # External integrations
  SlackBotToken: "xoxb-your-slack-bot-token"
  TeamsWebhookUrl: "https://your-teams-webhook-url"
  
  # Azure Key Vault (if using)
  AzureKeyVaultUrl: "https://your-keyvault.vault.azure.net/"
  AzureClientId: "your-azure-client-id"
  AzureClientSecret: "your-azure-client-secret"
  AzureTenantId: "your-azure-tenant-id"
---
apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: monitoring-grid
type: Opaque
stringData:
  SA_PASSWORD: "CHANGE_ME_IN_PRODUCTION_123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: monitoring-grid
type: Opaque
stringData:
  REDIS_PASSWORD: "CHANGE_ME_IN_PRODUCTION_123!"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-grid-tls
  namespace: monitoring-grid
type: kubernetes.io/tls
data:
  # Replace with your actual TLS certificate and key (base64 encoded)
  tls.crt: LS0tLS1CRUdJTi... # Your certificate here
  tls.key: LS0tLS1CRUdJTi... # Your private key here
