SELECT TOP (1000) [ExecutionID]
      ,[RunDate]
      ,[Hour]
      ,[IndicatorID]
      ,[IndicatorCode]
      ,[Amount]
      ,[Average]
      ,[Deviation]
      ,[Result]
      ,[UpdatedDate]
  FROM [PopAI].[monitoring].[IndicatorsExecutionHistory]
